stages:
  prepare:
    cmd: uv run -m travel_agent.pipeline.prepare
    deps:
      - data/raw/geo-reviews-dataset-2023.csv
      - travel_agent/pipeline/prepare.py
    params:
      - prepare
    outs:
      - data/prepared
  analyze:
    cmd: uv run -m travel_agent.pipeline.analyze
    deps:
      - data/raw/geo-reviews-dataset-2023.csv
      - travel_agent/pipeline/analyze.py
    params:
      - analyze
    outs:
      - data/analyze
  generate_moscow_rag_questions:
    cmd: uv run -m travel_agent.pipeline.generate_rag_questions --dataset data/prepared/moskva.csv
    deps:
      - data/prepared/moskva.csv
      - travel_agent/pipeline/generate_rag_questions.py
    params:
      - generate_rag_questions
    outs:
      - data/questions/rag/moskva.csv
  generate_saint_petersburg_rag_questions:
    cmd: uv run -m travel_agent.pipeline.generate_rag_questions --dataset data/prepared/sankt-peterburg.csv
    deps:
      - data/prepared/sankt-peterburg.csv
      - travel_agent/pipeline/generate_rag_questions.py
    params:
      - generate_rag_questions
    outs:
      - data/questions/rag/sankt-peterburg.csv
  generate_norm_rubrics_questions:
    cmd: uv run -m travel_agent.pipeline.generate_embed_questions --dataset data/prepared/normal_rubrics_15886.csv
    deps:
      - data/prepared/normal_rubrics_15886.csv
      - travel_agent/pipeline/generate_embed_questions.py
    params:
      - generate_embed_questions
    outs:
      - data/questions/embed/normal_rubrics_15886.csv
