stages:
  prepare:
    cmd: uv run -m travel_agent.pipeline.prepare
    deps:
    - data/raw/geo-reviews-dataset-2023.csv
    - travel_agent/pipeline/prepare.py
    params:
    - prepare
    outs:
    - data/prepared
  generate_moscow_rag_questions:
    cmd: uv run -m travel_agent.pipeline.generate_rag_questions --dataset data/prepared/moskva.csv
    deps:
    - data/prepared/moskva.csv
    - travel_agent/pipeline/generate_rag_questions.py
    params:
    - generate_rag_questions
    outs:
    - data/questions/moskva.csv
  generate_saint_petersburg_rag_questions:
    cmd: uv run -m travel_agent.pipeline.generate_rag_questions --dataset data/prepared/sankt-peterburg.csv
    deps:
    - data/prepared/sankt-peterburg.csv
    - travel_agent/pipeline/generate_rag_questions.py
    params:
    - generate_rag_questions
    outs:
    - data/questions/sankt-peterburg.csv
