stages:
  prepare:
    cmd: uv run travel_agent/pipeline/prepare.py
    deps:
    - travel_agent/pipeline/prepare.py
    params:
    - prepare
    outs:
    - data/prepared
  generate_questions:
    cmd: uv run travel_agent/pipeline/generate_questions.py
    deps:
    - travel_agent/pipeline/generate_questions.py
    params:
    - generate_questions
    outs:
    - data/questions
