stages:
  prepare:
    cmd: uv run -m travel_agent.pipeline.prepare
    deps:
    - data/raw/geo-reviews-dataset-2023.csv
    - travel_agent/pipeline/prepare.py
    params:
    - prepare
    outs:
    - data/prepared
  generate_questions:
    cmd: uv run -m travel_agent.pipeline.generate_questions
    deps:
    - data/prepared/moskva.csv
    - travel_agent/pipeline/generate_questions.py
    params:
    - generate_questions
    outs:
    - data/questions/questions.csv
