prepare:
  random_state: 42
  dataset: data/raw/geo-reviews-dataset-2023.csv
  out_dir: data/prepared
  cities:
    - Москва
    - Санкт-Петербург

analyze:
  dataset: data/raw/geo-reviews-dataset-2023.csv
  out_dir: data/analyze
  top_n_phrases: 50
  top_n_phrases_ngram:
    - 2
    - 4

generate_rag_questions:
  out_dir: data/questions/rag
  n_questions:
    rubric: 20
    address: 20
    rating_and_rubric: 10
    rating: 3
  keywords:
    - "вкусный кофе"
    - "японская кухня"
    - "удобное расположение"
    - "качественный сервис"
    - "приятная атмосфера"
    - "ноготочки"

generate_embed_questions:
  out_dir: data/questions/embed
  rubric_to_query:
    "Кафе": "Где можно вкусно поесть в городе?"
    "Кофейня": "Где попить хороший кофе?"
    "Салон красоты": "Где можно сделать стрижку или укладку?"
    "Ремонт телефонов": "Где починить телефон?"
    "Фитнес-клуб": "Где позаниматься спортом?"
    "Бассейн": "Где есть бассейны или аквапарки?"
    "Пейнтбол": "Где поиграть в пейнтбол или лазертаг?"
    "Окна": "Где заказать окна?"
    "Подарки": "Где купить необычный подарок?"
