prepare:
  dataset: data/raw/geo-reviews-dataset-2023.csv
  out_dir: data/prepared
  cities:
    - Москва
    - Санкт-Петербург

generate_questions:
  seed: 2025
  dataset: data/prepared/moskva.csv
  out_dir: data/questions
  out_filename: questions.csv

  n_questions:
    rubric: 20
    address: 20
    rating_and_rubric: 10
    keyword: 5
    rating: 3
  keywords:
    - "вкусный кофе"
    - "удобное расположение"
    - "онлайн-сервис"
    - "атмосфера"
    - "объёмные ресницы"

embed:
  todo: true
