prepare:
  random_state: 42
  dataset: data/raw/geo-reviews-dataset-2023.csv
  out_dir: data/prepared
  cities:
    - Москва
    - Санкт-Петербург

analyze:
  dataset: data/raw/geo-reviews-dataset-2023.csv
  out_dir: data/analyze
  top_n: 5

generate_rag_questions:
  out_dir: data/questions/rag
  n_questions:
    rubric: 30
    address: 5
    rating_and_rubric: 20
  keywords:
    - "вкусный кофе"
    - "японская кухня"
    - "удобное расположение"
    - "качественный сервис"
    - "приятная атмосфера"
    - "ноготочки"
    - "увлекательная экскурсия"
    - "интересное представление"
    - "удобный доступ"
    - "красивый вид"
    - "лучшие завтраки"
    - "ужас!"
    - "огромная благодарность"

generate_embed_questions:
  dataset: data/prepared/normal_rubrics_15886.csv
  out_dir: data/questions/embed_eval
