[project]
name = "travel-agent"
version = "0.1.0"
description = "LLM agent with retrieval"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastembed>=0.6.0",
    "huggingface-hub>=0.28.1",
    "ipykernel>=6.29.5",
    "nltk>=3.9.1",
    "pandas>=2.2.3",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
    "qdrant-client>=1.12.1",
    "seaborn>=0.13.2",
    "sentence-transformers>=2.6.1",
    "smolagents>=1.9.2",
    "torch>=2.6.0",
    "transformers>=4.50.3",
    "wordcloud>=1.9.4",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "jupyter>=1.1.1",
    "notebook>=7.3.2",
    "pre-commit>=4.1.0",
    "huggingface>=0.0.1",
    "tqdm>=4.67.1",
    "transliterate>=1.10.2",
    "loguru>=0.7.3",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
