[project]
name = "travel-agent"
version = "0.1.0"
description = "LLM agent with retrieval"
readme = "README.md"
authors = [
    { name = "Тот самый белый", email = "kirazu@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastembed>=0.6.1",
    "huggingface-hub[hf-xet]>=0.30.2",
    "loguru>=0.7.3",
    "matplotlib>=3.10.1",
    "nltk>=3.9.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "pydantic>=2.11.3",
    "python-dotenv>=1.1.0",
    "qdrant-client>=1.13.3",
    "seaborn>=0.13.2",
    "sentence-transformers>=4.0.2",
    "smolagents>=1.13.0",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
    "transformers>=4.51.2",
    "transliterate>=1.10.2",
    "wordcloud>=1.9.4",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pre-commit>=4.2.0",
    "ruff>=0.11.5",
]

[project.scripts]
travel-agent = "travel_agent:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
