apiVersion: v1
kind: Service
metadata:
  name: caddy
spec:
  selector:
    app: caddy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: app
      port: 8000
      targetPort: 8000
    - name: alt
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2.10.0-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8000
            - containerPort: 8080
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: html
              mountPath: /srv/html
            - name: caddy-data
              mountPath: /data
            - name: caddy-config
              mountPath: /config
      volumes:
        - name: caddyfile
          configMap:
            name: caddyfile
        - name: html
          persistentVolumeClaim:
            claimName: html-pvc
        - name: caddy-data
          emptyDir: {}
        - name: caddy-config
          emptyDir: {}
