apiVersion: v1
kind: ConfigMap
metadata:
  name: travel-agent-config
data:
  HF_HOME: /hf_cache
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tracing:4317
  COLLECTOR_ENDPOINT: http://tracing:6006/v1/traces
  QDRANT_URL: http://qdrant:6333
